#!/usr/bin/env ruby -w -Ilib

require 'parser'
require 'defs'
require 'prelude'

def printenv(program)
  if program.nil?
    "no program"
  else
    begin
      program.flatten.map(&:identifier).map(&:name).join(', ')
    rescue => _
      "error getting env"
    end
  end
end

def run_eval(fun, programs)
  base, env = programs
  base = base.flatten
  env = env.flatten
  body = fun.body

  case body
  when NativeRubyCode
    body.body.call([base,env], fun)
  when NumberType
    body
  when StringType
    body.value
  when FunCall
    target = [base, env].flatten.
      find { |f| f.identifier == body.identifier }

    if target.nil?
      raise "Can't find function #{body.identifier} (from #{fun.identifier}).\nAvail: #{program.map(&:identifier).join(', ')}"
    end

    args = target.args

    top_vars   = base.map(&:identifier)
    local_vars = env.map(&:identifier)

    if ENV['DEBUG']
      puts "WARNING(#{body.identifier}): top_vars was : #{top_vars.map(&:name)}"
      puts "WARNING(#{body.identifier}): local_vars was : #{local_vars.map(&:name)}"
    end

    if body.args.value.count < args.value.count
      raise 'Currying functions is not supported (yet)'
    end

    new_env = body.args.value.zip(args.value).map do |val, arg_def|
      param = FunDef.new(nil,FunCallArgs.new([]),val)

      FunDef.new(
        arg_def,
        FunCallArgs.new([]),
        run_eval(param, [base, env]))
    end

    if ENV['DEBUG']
      puts "DEBUG: Adding to env for #{body.identifier}: #{new_env.map(&:identifier)}"
      [base, env].flatten.each_with_index do |s, i|
        puts "#{i}: #{s&.identifier}, #{s&.body}"
      end
      puts "END DEBUG"
    end

    fun = [base,env].flatten.find { |f| f.identifier == body.identifier }

    if fun.nil?
      raise FunctionNotFound, "Can't find function: #{body.identifier}"
    end

    run_eval(fun, [base, new_env])
  else
    raise UnsupportedType, "#{body.class} called in #{fun}"
  end
end


def run_types(fun, programs)
end

DOMAINS = {
  "Int" => NumberType,
  "String" => StringType,
}
def apply_types(program)
  tds = program.select { |s| s.is_a? TypeDef }
  sts = program.select { |s| s.is_a? FunDef }
  tds.each do |td|
    sts.
      find { |fun| (fun.identifier.name == td.identifier) && fun.is_a?(FunDef) }.
      tap do |fun_def|
        fun_def.domains = Domains.new td.domains.map { |a| Domain.new DOMAINS.fetch(a) }
      end
  end
  sts.each do |st|
    # TODO: type propagation
    # depth-first search, and then propagate up and laterally
  end
  sts
end

def apply_prelude(program)
  Prelude.apply(program)
end

def banner
  puts(<<EOS)
USAGE: ./fr <your source file>

This will run your FR file.
EOS
end

EntryPointNotFound = Class.new RuntimeError
FunctionNotFound   = Class.new RuntimeError
UnsupportedType    = Class.new RuntimeError

parser = Parser.new
ENTRY_POINT = "main"

file = ARGV[0]
if file
  # parse and type-check
  program = parser.parse(File.read(file).strip)
  program = apply_prelude(program)
  program = apply_types(program)

  if ENV['DEBUG'] # check typing
    puts program.map(&:to_s)
  else # run the program
    entry = program.find { |fun| fun.identifier.name == ENTRY_POINT && fun.is_a?(FunDef) }

    stack = [[program], []]

    if entry.nil?
      raise EntryPointNotFound, "Couldn't find entry point: #{ENTRY_POINT}"
    end
    puts "\n#{run_eval(entry, stack)}"
  end
else
  banner
end

# vim: set ft=ruby:
